# http://about.travis-ci.org/docs/user/build-configuration/
language: python
python: 3.5

install:
  - pip install -r requirements.txt
  - buildout -q -N -t 3 install instance
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/instance start
after_failure:
  - buildout annotate
  - firefox -v

